services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - composer-cache:/root/.composer/cache
    working_dir: /app
    tty: true                      # ✅ garde le conteneur vivant
    stdin_open: true               # ✅ équivalent du flag -it
    environment:
      - XDEBUG_MODE=coverage

volumes:
  composer-cache: